namespace EMRge
{
    partial class FormMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormMain));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuGradientPanel2 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.BtnLogOut = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.LblHospitalMotto = new Bunifu.UI.WinForms.BunifuLabel();
            this.LblHospitalName = new Bunifu.UI.WinForms.BunifuLabel();
            this.LblDate = new Bunifu.UI.WinForms.BunifuLabel();
            this.LblLoggedAs = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.btnBilling = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnStaff = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDashboard = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnPatients = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnInventory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnExamination = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLaboratory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuGradientPanel2.SuspendLayout();
            this.bunifuGradientPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuGradientPanel2
            // 
            this.bunifuGradientPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel2.BackgroundImage")));
            this.bunifuGradientPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel2.BorderRadius = 1;
            this.bunifuGradientPanel2.Controls.Add(this.BtnLogOut);
            this.bunifuGradientPanel2.Controls.Add(this.LblHospitalMotto);
            this.bunifuGradientPanel2.Controls.Add(this.LblHospitalName);
            this.bunifuGradientPanel2.Controls.Add(this.LblDate);
            this.bunifuGradientPanel2.Controls.Add(this.LblLoggedAs);
            this.bunifuGradientPanel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuGradientPanel2.GradientBottomLeft = System.Drawing.Color.White;
            this.bunifuGradientPanel2.GradientBottomRight = System.Drawing.Color.White;
            this.bunifuGradientPanel2.GradientTopLeft = System.Drawing.Color.White;
            this.bunifuGradientPanel2.GradientTopRight = System.Drawing.Color.White;
            this.bunifuGradientPanel2.Location = new System.Drawing.Point(217, 0);
            this.bunifuGradientPanel2.Margin = new System.Windows.Forms.Padding(0, 3, 3, 3);
            this.bunifuGradientPanel2.Name = "bunifuGradientPanel2";
            this.bunifuGradientPanel2.Quality = 10;
            this.bunifuGradientPanel2.Size = new System.Drawing.Size(1127, 58);
            this.bunifuGradientPanel2.TabIndex = 1;
            // 
            // BtnLogOut
            // 
            this.BtnLogOut.AllowAnimations = true;
            this.BtnLogOut.AllowMouseEffects = true;
            this.BtnLogOut.AllowToggling = false;
            this.BtnLogOut.AnimationSpeed = 200;
            this.BtnLogOut.AutoGenerateColors = false;
            this.BtnLogOut.AutoRoundBorders = false;
            this.BtnLogOut.AutoSizeLeftIcon = true;
            this.BtnLogOut.AutoSizeRightIcon = true;
            this.BtnLogOut.BackColor = System.Drawing.Color.Transparent;
            this.BtnLogOut.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(188)))));
            this.BtnLogOut.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnLogOut.BackgroundImage")));
            this.BtnLogOut.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLogOut.ButtonText = "Log Out";
            this.BtnLogOut.ButtonTextMarginLeft = 0;
            this.BtnLogOut.ColorContrastOnClick = 45;
            this.BtnLogOut.ColorContrastOnHover = 45;
            this.BtnLogOut.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.BtnLogOut.CustomizableEdges = borderEdges1;
            this.BtnLogOut.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnLogOut.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnLogOut.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnLogOut.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnLogOut.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnLogOut.Font = new System.Drawing.Font("Open Sans SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnLogOut.ForeColor = System.Drawing.Color.Black;
            this.BtnLogOut.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnLogOut.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnLogOut.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnLogOut.IconMarginLeft = 11;
            this.BtnLogOut.IconPadding = 10;
            this.BtnLogOut.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnLogOut.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnLogOut.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnLogOut.IconSize = 25;
            this.BtnLogOut.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(188)))));
            this.BtnLogOut.IdleBorderRadius = 1;
            this.BtnLogOut.IdleBorderThickness = 1;
            this.BtnLogOut.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(188)))));
            this.BtnLogOut.IdleIconLeftImage = null;
            this.BtnLogOut.IdleIconRightImage = null;
            this.BtnLogOut.IndicateFocus = false;
            this.BtnLogOut.Location = new System.Drawing.Point(983, 27);
            this.BtnLogOut.Margin = new System.Windows.Forms.Padding(4);
            this.BtnLogOut.Name = "BtnLogOut";
            this.BtnLogOut.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnLogOut.OnDisabledState.BorderRadius = 1;
            this.BtnLogOut.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLogOut.OnDisabledState.BorderThickness = 1;
            this.BtnLogOut.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnLogOut.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnLogOut.OnDisabledState.IconLeftImage = null;
            this.BtnLogOut.OnDisabledState.IconRightImage = null;
            this.BtnLogOut.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(168)))), ((int)(((byte)(140)))));
            this.BtnLogOut.onHoverState.BorderRadius = 1;
            this.BtnLogOut.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLogOut.onHoverState.BorderThickness = 1;
            this.BtnLogOut.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(168)))), ((int)(((byte)(140)))));
            this.BtnLogOut.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnLogOut.onHoverState.IconLeftImage = null;
            this.BtnLogOut.onHoverState.IconRightImage = null;
            this.BtnLogOut.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(188)))));
            this.BtnLogOut.OnIdleState.BorderRadius = 1;
            this.BtnLogOut.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLogOut.OnIdleState.BorderThickness = 1;
            this.BtnLogOut.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(188)))));
            this.BtnLogOut.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.BtnLogOut.OnIdleState.IconLeftImage = null;
            this.BtnLogOut.OnIdleState.IconRightImage = null;
            this.BtnLogOut.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(137)))), ((int)(((byte)(100)))));
            this.BtnLogOut.OnPressedState.BorderRadius = 1;
            this.BtnLogOut.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLogOut.OnPressedState.BorderThickness = 1;
            this.BtnLogOut.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(137)))), ((int)(((byte)(100)))));
            this.BtnLogOut.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnLogOut.OnPressedState.IconLeftImage = null;
            this.BtnLogOut.OnPressedState.IconRightImage = null;
            this.BtnLogOut.Size = new System.Drawing.Size(73, 27);
            this.BtnLogOut.TabIndex = 2;
            this.BtnLogOut.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnLogOut.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnLogOut.TextMarginLeft = 0;
            this.BtnLogOut.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnLogOut.UseDefaultRadiusAndThickness = true;
            this.BtnLogOut.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // LblHospitalMotto
            // 
            this.LblHospitalMotto.AllowParentOverrides = false;
            this.LblHospitalMotto.AutoEllipsis = false;
            this.LblHospitalMotto.AutoSize = false;
            this.LblHospitalMotto.CursorType = null;
            this.LblHospitalMotto.Font = new System.Drawing.Font("Open Sans", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LblHospitalMotto.ForeColor = System.Drawing.Color.Black;
            this.LblHospitalMotto.Location = new System.Drawing.Point(85, 34);
            this.LblHospitalMotto.Margin = new System.Windows.Forms.Padding(0);
            this.LblHospitalMotto.Name = "LblHospitalMotto";
            this.LblHospitalMotto.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblHospitalMotto.Size = new System.Drawing.Size(260, 18);
            this.LblHospitalMotto.TabIndex = 5;
            this.LblHospitalMotto.Text = "Capital of health.";
            this.LblHospitalMotto.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.LblHospitalMotto.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // LblHospitalName
            // 
            this.LblHospitalName.AllowParentOverrides = false;
            this.LblHospitalName.AutoEllipsis = false;
            this.LblHospitalName.AutoSize = false;
            this.LblHospitalName.CursorType = null;
            this.LblHospitalName.Font = new System.Drawing.Font("Space Grotesk", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LblHospitalName.ForeColor = System.Drawing.Color.Black;
            this.LblHospitalName.Location = new System.Drawing.Point(85, 12);
            this.LblHospitalName.Margin = new System.Windows.Forms.Padding(0);
            this.LblHospitalName.Name = "LblHospitalName";
            this.LblHospitalName.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblHospitalName.Size = new System.Drawing.Size(260, 19);
            this.LblHospitalName.TabIndex = 4;
            this.LblHospitalName.Text = "Silver Crest Hospital";
            this.LblHospitalName.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.LblHospitalName.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // LblDate
            // 
            this.LblDate.AllowParentOverrides = false;
            this.LblDate.AutoEllipsis = false;
            this.LblDate.AutoSize = false;
            this.LblDate.CursorType = null;
            this.LblDate.Font = new System.Drawing.Font("Open Sans SemiBold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LblDate.ForeColor = System.Drawing.Color.Black;
            this.LblDate.Location = new System.Drawing.Point(656, 12);
            this.LblDate.Name = "LblDate";
            this.LblDate.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblDate.Size = new System.Drawing.Size(246, 31);
            this.LblDate.TabIndex = 3;
            this.LblDate.Text = "Thursday, October 19th, 2022";
            this.LblDate.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.LblDate.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // LblLoggedAs
            // 
            this.LblLoggedAs.AllowParentOverrides = false;
            this.LblLoggedAs.AutoEllipsis = false;
            this.LblLoggedAs.AutoSize = false;
            this.LblLoggedAs.CursorType = null;
            this.LblLoggedAs.Font = new System.Drawing.Font("Open Sans", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LblLoggedAs.ForeColor = System.Drawing.Color.Black;
            this.LblLoggedAs.Location = new System.Drawing.Point(919, 4);
            this.LblLoggedAs.Name = "LblLoggedAs";
            this.LblLoggedAs.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblLoggedAs.Size = new System.Drawing.Size(187, 19);
            this.LblLoggedAs.TabIndex = 0;
            this.LblLoggedAs.Text = "Logged in as";
            this.LblLoggedAs.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.LblLoggedAs.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuSeparator1);
            this.bunifuGradientPanel1.Controls.Add(this.btnBilling);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuGradientPanel1.Controls.Add(this.btnStaff);
            this.bunifuGradientPanel1.Controls.Add(this.btnDashboard);
            this.bunifuGradientPanel1.Controls.Add(this.btnPatients);
            this.bunifuGradientPanel1.Controls.Add(this.btnInventory);
            this.bunifuGradientPanel1.Controls.Add(this.btnExamination);
            this.bunifuGradientPanel1.Controls.Add(this.btnLaboratory);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Margin = new System.Windows.Forms.Padding(4, 4, 0, 4);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(217, 821);
            this.bunifuGradientPanel1.TabIndex = 0;
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.ForeColor = System.Drawing.Color.White;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.White;
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator1.LineThickness = 5;
            this.bunifuSeparator1.Location = new System.Drawing.Point(1, 105);
            this.bunifuSeparator1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(217, 14);
            this.bunifuSeparator1.TabIndex = 16;
            // 
            // btnBilling
            // 
            this.btnBilling.AllowAnimations = true;
            this.btnBilling.AllowMouseEffects = true;
            this.btnBilling.AllowToggling = false;
            this.btnBilling.AnimationSpeed = 200;
            this.btnBilling.AutoGenerateColors = false;
            this.btnBilling.AutoRoundBorders = false;
            this.btnBilling.AutoSizeLeftIcon = true;
            this.btnBilling.AutoSizeRightIcon = true;
            this.btnBilling.BackColor = System.Drawing.Color.Transparent;
            this.btnBilling.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnBilling.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBilling.BackgroundImage")));
            this.btnBilling.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBilling.ButtonText = "Billing";
            this.btnBilling.ButtonTextMarginLeft = 0;
            this.btnBilling.ColorContrastOnClick = 45;
            this.btnBilling.ColorContrastOnHover = 45;
            this.btnBilling.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnBilling.CustomizableEdges = borderEdges2;
            this.btnBilling.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBilling.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBilling.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBilling.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBilling.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBilling.Font = new System.Drawing.Font("Open Sans SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBilling.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnBilling.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBilling.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBilling.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBilling.IconMarginLeft = 11;
            this.btnBilling.IconPadding = 10;
            this.btnBilling.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBilling.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBilling.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBilling.IconSize = 25;
            this.btnBilling.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnBilling.IdleBorderRadius = 1;
            this.btnBilling.IdleBorderThickness = 1;
            this.btnBilling.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnBilling.IdleIconLeftImage = null;
            this.btnBilling.IdleIconRightImage = null;
            this.btnBilling.IndicateFocus = false;
            this.btnBilling.Location = new System.Drawing.Point(0, 484);
            this.btnBilling.Margin = new System.Windows.Forms.Padding(4);
            this.btnBilling.Name = "btnBilling";
            this.btnBilling.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBilling.OnDisabledState.BorderRadius = 1;
            this.btnBilling.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBilling.OnDisabledState.BorderThickness = 1;
            this.btnBilling.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBilling.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBilling.OnDisabledState.IconLeftImage = null;
            this.btnBilling.OnDisabledState.IconRightImage = null;
            this.btnBilling.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(104)))), ((int)(((byte)(94)))));
            this.btnBilling.onHoverState.BorderRadius = 1;
            this.btnBilling.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBilling.onHoverState.BorderThickness = 1;
            this.btnBilling.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(104)))), ((int)(((byte)(94)))));
            this.btnBilling.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBilling.onHoverState.IconLeftImage = null;
            this.btnBilling.onHoverState.IconRightImage = null;
            this.btnBilling.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnBilling.OnIdleState.BorderRadius = 1;
            this.btnBilling.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBilling.OnIdleState.BorderThickness = 1;
            this.btnBilling.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnBilling.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnBilling.OnIdleState.IconLeftImage = null;
            this.btnBilling.OnIdleState.IconRightImage = null;
            this.btnBilling.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(68)))), ((int)(((byte)(60)))));
            this.btnBilling.OnPressedState.BorderRadius = 1;
            this.btnBilling.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBilling.OnPressedState.BorderThickness = 1;
            this.btnBilling.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(68)))), ((int)(((byte)(60)))));
            this.btnBilling.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBilling.OnPressedState.IconLeftImage = null;
            this.btnBilling.OnPressedState.IconRightImage = null;
            this.btnBilling.Size = new System.Drawing.Size(217, 48);
            this.btnBilling.TabIndex = 14;
            this.btnBilling.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBilling.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBilling.TextMarginLeft = 0;
            this.btnBilling.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBilling.UseDefaultRadiusAndThickness = true;
            this.btnBilling.Click += new System.EventHandler(this.btnBilling_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Open Sans SemiBold", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(34, 46);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(140, 38);
            this.bunifuLabel1.TabIndex = 8;
            this.bunifuLabel1.Text = "Your all-in-one \r\nEMR and HMS solution";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Space Grotesk", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(65, 4);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(78, 35);
            this.bunifuLabel2.TabIndex = 0;
            this.bunifuLabel2.Text = "EMRge";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnStaff
            // 
            this.btnStaff.AllowAnimations = true;
            this.btnStaff.AllowMouseEffects = true;
            this.btnStaff.AllowToggling = false;
            this.btnStaff.AnimationSpeed = 200;
            this.btnStaff.AutoGenerateColors = false;
            this.btnStaff.AutoRoundBorders = false;
            this.btnStaff.AutoSizeLeftIcon = true;
            this.btnStaff.AutoSizeRightIcon = true;
            this.btnStaff.BackColor = System.Drawing.Color.Transparent;
            this.btnStaff.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnStaff.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnStaff.BackgroundImage")));
            this.btnStaff.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStaff.ButtonText = "Staff";
            this.btnStaff.ButtonTextMarginLeft = 0;
            this.btnStaff.ColorContrastOnClick = 45;
            this.btnStaff.ColorContrastOnHover = 45;
            this.btnStaff.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnStaff.CustomizableEdges = borderEdges3;
            this.btnStaff.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnStaff.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStaff.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStaff.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStaff.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnStaff.Font = new System.Drawing.Font("Open Sans SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnStaff.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnStaff.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnStaff.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnStaff.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnStaff.IconMarginLeft = 11;
            this.btnStaff.IconPadding = 10;
            this.btnStaff.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnStaff.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnStaff.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnStaff.IconSize = 25;
            this.btnStaff.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnStaff.IdleBorderRadius = 1;
            this.btnStaff.IdleBorderThickness = 1;
            this.btnStaff.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnStaff.IdleIconLeftImage = null;
            this.btnStaff.IdleIconRightImage = null;
            this.btnStaff.IndicateFocus = false;
            this.btnStaff.Location = new System.Drawing.Point(0, 428);
            this.btnStaff.Margin = new System.Windows.Forms.Padding(4);
            this.btnStaff.Name = "btnStaff";
            this.btnStaff.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStaff.OnDisabledState.BorderRadius = 1;
            this.btnStaff.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStaff.OnDisabledState.BorderThickness = 1;
            this.btnStaff.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStaff.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStaff.OnDisabledState.IconLeftImage = null;
            this.btnStaff.OnDisabledState.IconRightImage = null;
            this.btnStaff.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(104)))), ((int)(((byte)(94)))));
            this.btnStaff.onHoverState.BorderRadius = 1;
            this.btnStaff.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStaff.onHoverState.BorderThickness = 1;
            this.btnStaff.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(104)))), ((int)(((byte)(94)))));
            this.btnStaff.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnStaff.onHoverState.IconLeftImage = null;
            this.btnStaff.onHoverState.IconRightImage = null;
            this.btnStaff.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnStaff.OnIdleState.BorderRadius = 1;
            this.btnStaff.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStaff.OnIdleState.BorderThickness = 1;
            this.btnStaff.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnStaff.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnStaff.OnIdleState.IconLeftImage = null;
            this.btnStaff.OnIdleState.IconRightImage = null;
            this.btnStaff.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(68)))), ((int)(((byte)(60)))));
            this.btnStaff.OnPressedState.BorderRadius = 1;
            this.btnStaff.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStaff.OnPressedState.BorderThickness = 1;
            this.btnStaff.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(68)))), ((int)(((byte)(60)))));
            this.btnStaff.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnStaff.OnPressedState.IconLeftImage = null;
            this.btnStaff.OnPressedState.IconRightImage = null;
            this.btnStaff.Size = new System.Drawing.Size(217, 48);
            this.btnStaff.TabIndex = 13;
            this.btnStaff.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnStaff.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnStaff.TextMarginLeft = 0;
            this.btnStaff.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnStaff.UseDefaultRadiusAndThickness = true;
            this.btnStaff.Click += new System.EventHandler(this.btnStaff_Click);
            // 
            // btnDashboard
            // 
            this.btnDashboard.AllowAnimations = true;
            this.btnDashboard.AllowMouseEffects = true;
            this.btnDashboard.AllowToggling = false;
            this.btnDashboard.AnimationSpeed = 200;
            this.btnDashboard.AutoGenerateColors = false;
            this.btnDashboard.AutoRoundBorders = false;
            this.btnDashboard.AutoSizeLeftIcon = true;
            this.btnDashboard.AutoSizeRightIcon = true;
            this.btnDashboard.BackColor = System.Drawing.Color.Transparent;
            this.btnDashboard.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnDashboard.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDashboard.BackgroundImage")));
            this.btnDashboard.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.ButtonText = "Dashboard";
            this.btnDashboard.ButtonTextMarginLeft = 0;
            this.btnDashboard.ColorContrastOnClick = 45;
            this.btnDashboard.ColorContrastOnHover = 45;
            this.btnDashboard.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnDashboard.CustomizableEdges = borderEdges4;
            this.btnDashboard.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDashboard.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashboard.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDashboard.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDashboard.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDashboard.Font = new System.Drawing.Font("Open Sans SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDashboard.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDashboard.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashboard.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDashboard.IconMarginLeft = 11;
            this.btnDashboard.IconPadding = 10;
            this.btnDashboard.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDashboard.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashboard.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDashboard.IconSize = 25;
            this.btnDashboard.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnDashboard.IdleBorderRadius = 1;
            this.btnDashboard.IdleBorderThickness = 1;
            this.btnDashboard.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnDashboard.IdleIconLeftImage = null;
            this.btnDashboard.IdleIconRightImage = null;
            this.btnDashboard.IndicateFocus = false;
            this.btnDashboard.Location = new System.Drawing.Point(1, 148);
            this.btnDashboard.Margin = new System.Windows.Forms.Padding(4);
            this.btnDashboard.Name = "btnDashboard";
            this.btnDashboard.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashboard.OnDisabledState.BorderRadius = 1;
            this.btnDashboard.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.OnDisabledState.BorderThickness = 1;
            this.btnDashboard.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDashboard.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDashboard.OnDisabledState.IconLeftImage = null;
            this.btnDashboard.OnDisabledState.IconRightImage = null;
            this.btnDashboard.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(104)))), ((int)(((byte)(94)))));
            this.btnDashboard.onHoverState.BorderRadius = 1;
            this.btnDashboard.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.onHoverState.BorderThickness = 1;
            this.btnDashboard.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(104)))), ((int)(((byte)(94)))));
            this.btnDashboard.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.onHoverState.IconLeftImage = null;
            this.btnDashboard.onHoverState.IconRightImage = null;
            this.btnDashboard.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnDashboard.OnIdleState.BorderRadius = 1;
            this.btnDashboard.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.OnIdleState.BorderThickness = 1;
            this.btnDashboard.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnDashboard.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.OnIdleState.IconLeftImage = null;
            this.btnDashboard.OnIdleState.IconRightImage = null;
            this.btnDashboard.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(68)))), ((int)(((byte)(60)))));
            this.btnDashboard.OnPressedState.BorderRadius = 1;
            this.btnDashboard.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.OnPressedState.BorderThickness = 1;
            this.btnDashboard.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(68)))), ((int)(((byte)(60)))));
            this.btnDashboard.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.OnPressedState.IconLeftImage = null;
            this.btnDashboard.OnPressedState.IconRightImage = null;
            this.btnDashboard.Size = new System.Drawing.Size(217, 48);
            this.btnDashboard.TabIndex = 1;
            this.btnDashboard.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDashboard.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDashboard.TextMarginLeft = 0;
            this.btnDashboard.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDashboard.UseDefaultRadiusAndThickness = true;
            this.btnDashboard.Click += new System.EventHandler(this.btnDashboard_Click);
            // 
            // btnPatients
            // 
            this.btnPatients.AllowAnimations = true;
            this.btnPatients.AllowMouseEffects = true;
            this.btnPatients.AllowToggling = false;
            this.btnPatients.AnimationSpeed = 200;
            this.btnPatients.AutoGenerateColors = false;
            this.btnPatients.AutoRoundBorders = false;
            this.btnPatients.AutoSizeLeftIcon = true;
            this.btnPatients.AutoSizeRightIcon = true;
            this.btnPatients.BackColor = System.Drawing.Color.Transparent;
            this.btnPatients.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnPatients.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPatients.BackgroundImage")));
            this.btnPatients.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPatients.ButtonText = "Patients";
            this.btnPatients.ButtonTextMarginLeft = 0;
            this.btnPatients.ColorContrastOnClick = 45;
            this.btnPatients.ColorContrastOnHover = 45;
            this.btnPatients.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnPatients.CustomizableEdges = borderEdges5;
            this.btnPatients.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPatients.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPatients.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPatients.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPatients.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnPatients.Font = new System.Drawing.Font("Open Sans SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPatients.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnPatients.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPatients.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPatients.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnPatients.IconMarginLeft = 11;
            this.btnPatients.IconPadding = 10;
            this.btnPatients.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPatients.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPatients.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPatients.IconSize = 25;
            this.btnPatients.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnPatients.IdleBorderRadius = 1;
            this.btnPatients.IdleBorderThickness = 1;
            this.btnPatients.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnPatients.IdleIconLeftImage = null;
            this.btnPatients.IdleIconRightImage = null;
            this.btnPatients.IndicateFocus = false;
            this.btnPatients.Location = new System.Drawing.Point(1, 204);
            this.btnPatients.Margin = new System.Windows.Forms.Padding(4);
            this.btnPatients.Name = "btnPatients";
            this.btnPatients.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPatients.OnDisabledState.BorderRadius = 1;
            this.btnPatients.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPatients.OnDisabledState.BorderThickness = 1;
            this.btnPatients.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPatients.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPatients.OnDisabledState.IconLeftImage = null;
            this.btnPatients.OnDisabledState.IconRightImage = null;
            this.btnPatients.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(104)))), ((int)(((byte)(94)))));
            this.btnPatients.onHoverState.BorderRadius = 1;
            this.btnPatients.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPatients.onHoverState.BorderThickness = 1;
            this.btnPatients.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(104)))), ((int)(((byte)(94)))));
            this.btnPatients.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnPatients.onHoverState.IconLeftImage = null;
            this.btnPatients.onHoverState.IconRightImage = null;
            this.btnPatients.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnPatients.OnIdleState.BorderRadius = 1;
            this.btnPatients.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPatients.OnIdleState.BorderThickness = 1;
            this.btnPatients.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnPatients.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnPatients.OnIdleState.IconLeftImage = null;
            this.btnPatients.OnIdleState.IconRightImage = null;
            this.btnPatients.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(68)))), ((int)(((byte)(60)))));
            this.btnPatients.OnPressedState.BorderRadius = 1;
            this.btnPatients.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPatients.OnPressedState.BorderThickness = 1;
            this.btnPatients.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(68)))), ((int)(((byte)(60)))));
            this.btnPatients.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnPatients.OnPressedState.IconLeftImage = null;
            this.btnPatients.OnPressedState.IconRightImage = null;
            this.btnPatients.Size = new System.Drawing.Size(217, 48);
            this.btnPatients.TabIndex = 9;
            this.btnPatients.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPatients.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPatients.TextMarginLeft = 0;
            this.btnPatients.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnPatients.UseDefaultRadiusAndThickness = true;
            this.btnPatients.Click += new System.EventHandler(this.btnPatients_Click);
            // 
            // btnInventory
            // 
            this.btnInventory.AllowAnimations = true;
            this.btnInventory.AllowMouseEffects = true;
            this.btnInventory.AllowToggling = false;
            this.btnInventory.AnimationSpeed = 200;
            this.btnInventory.AutoGenerateColors = false;
            this.btnInventory.AutoRoundBorders = false;
            this.btnInventory.AutoSizeLeftIcon = true;
            this.btnInventory.AutoSizeRightIcon = true;
            this.btnInventory.BackColor = System.Drawing.Color.Transparent;
            this.btnInventory.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnInventory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnInventory.BackgroundImage")));
            this.btnInventory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInventory.ButtonText = "Inventory";
            this.btnInventory.ButtonTextMarginLeft = 0;
            this.btnInventory.ColorContrastOnClick = 45;
            this.btnInventory.ColorContrastOnHover = 45;
            this.btnInventory.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnInventory.CustomizableEdges = borderEdges6;
            this.btnInventory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnInventory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInventory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInventory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInventory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnInventory.Font = new System.Drawing.Font("Open Sans SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnInventory.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnInventory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInventory.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnInventory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnInventory.IconMarginLeft = 11;
            this.btnInventory.IconPadding = 10;
            this.btnInventory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnInventory.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnInventory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnInventory.IconSize = 25;
            this.btnInventory.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnInventory.IdleBorderRadius = 1;
            this.btnInventory.IdleBorderThickness = 1;
            this.btnInventory.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnInventory.IdleIconLeftImage = null;
            this.btnInventory.IdleIconRightImage = null;
            this.btnInventory.IndicateFocus = false;
            this.btnInventory.Location = new System.Drawing.Point(0, 372);
            this.btnInventory.Margin = new System.Windows.Forms.Padding(4);
            this.btnInventory.Name = "btnInventory";
            this.btnInventory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInventory.OnDisabledState.BorderRadius = 1;
            this.btnInventory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInventory.OnDisabledState.BorderThickness = 1;
            this.btnInventory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInventory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInventory.OnDisabledState.IconLeftImage = null;
            this.btnInventory.OnDisabledState.IconRightImage = null;
            this.btnInventory.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(104)))), ((int)(((byte)(94)))));
            this.btnInventory.onHoverState.BorderRadius = 1;
            this.btnInventory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInventory.onHoverState.BorderThickness = 1;
            this.btnInventory.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(104)))), ((int)(((byte)(94)))));
            this.btnInventory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnInventory.onHoverState.IconLeftImage = null;
            this.btnInventory.onHoverState.IconRightImage = null;
            this.btnInventory.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnInventory.OnIdleState.BorderRadius = 1;
            this.btnInventory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInventory.OnIdleState.BorderThickness = 1;
            this.btnInventory.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnInventory.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnInventory.OnIdleState.IconLeftImage = null;
            this.btnInventory.OnIdleState.IconRightImage = null;
            this.btnInventory.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(68)))), ((int)(((byte)(60)))));
            this.btnInventory.OnPressedState.BorderRadius = 1;
            this.btnInventory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInventory.OnPressedState.BorderThickness = 1;
            this.btnInventory.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(68)))), ((int)(((byte)(60)))));
            this.btnInventory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnInventory.OnPressedState.IconLeftImage = null;
            this.btnInventory.OnPressedState.IconRightImage = null;
            this.btnInventory.Size = new System.Drawing.Size(217, 48);
            this.btnInventory.TabIndex = 12;
            this.btnInventory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnInventory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnInventory.TextMarginLeft = 0;
            this.btnInventory.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnInventory.UseDefaultRadiusAndThickness = true;
            this.btnInventory.Click += new System.EventHandler(this.btnInventory_Click);
            // 
            // btnExamination
            // 
            this.btnExamination.AllowAnimations = true;
            this.btnExamination.AllowMouseEffects = true;
            this.btnExamination.AllowToggling = false;
            this.btnExamination.AnimationSpeed = 200;
            this.btnExamination.AutoGenerateColors = false;
            this.btnExamination.AutoRoundBorders = false;
            this.btnExamination.AutoSizeLeftIcon = true;
            this.btnExamination.AutoSizeRightIcon = true;
            this.btnExamination.BackColor = System.Drawing.Color.Transparent;
            this.btnExamination.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnExamination.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnExamination.BackgroundImage")));
            this.btnExamination.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExamination.ButtonText = "Examination";
            this.btnExamination.ButtonTextMarginLeft = 0;
            this.btnExamination.ColorContrastOnClick = 45;
            this.btnExamination.ColorContrastOnHover = 45;
            this.btnExamination.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnExamination.CustomizableEdges = borderEdges7;
            this.btnExamination.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnExamination.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExamination.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExamination.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExamination.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnExamination.Font = new System.Drawing.Font("Open Sans SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnExamination.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnExamination.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnExamination.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnExamination.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnExamination.IconMarginLeft = 11;
            this.btnExamination.IconPadding = 10;
            this.btnExamination.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnExamination.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnExamination.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnExamination.IconSize = 25;
            this.btnExamination.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnExamination.IdleBorderRadius = 1;
            this.btnExamination.IdleBorderThickness = 1;
            this.btnExamination.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnExamination.IdleIconLeftImage = null;
            this.btnExamination.IdleIconRightImage = null;
            this.btnExamination.IndicateFocus = false;
            this.btnExamination.Location = new System.Drawing.Point(1, 260);
            this.btnExamination.Margin = new System.Windows.Forms.Padding(4);
            this.btnExamination.Name = "btnExamination";
            this.btnExamination.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExamination.OnDisabledState.BorderRadius = 1;
            this.btnExamination.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExamination.OnDisabledState.BorderThickness = 1;
            this.btnExamination.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExamination.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExamination.OnDisabledState.IconLeftImage = null;
            this.btnExamination.OnDisabledState.IconRightImage = null;
            this.btnExamination.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(104)))), ((int)(((byte)(94)))));
            this.btnExamination.onHoverState.BorderRadius = 1;
            this.btnExamination.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExamination.onHoverState.BorderThickness = 1;
            this.btnExamination.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(104)))), ((int)(((byte)(94)))));
            this.btnExamination.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnExamination.onHoverState.IconLeftImage = null;
            this.btnExamination.onHoverState.IconRightImage = null;
            this.btnExamination.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnExamination.OnIdleState.BorderRadius = 1;
            this.btnExamination.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExamination.OnIdleState.BorderThickness = 1;
            this.btnExamination.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnExamination.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnExamination.OnIdleState.IconLeftImage = null;
            this.btnExamination.OnIdleState.IconRightImage = null;
            this.btnExamination.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(68)))), ((int)(((byte)(60)))));
            this.btnExamination.OnPressedState.BorderRadius = 1;
            this.btnExamination.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExamination.OnPressedState.BorderThickness = 1;
            this.btnExamination.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(68)))), ((int)(((byte)(60)))));
            this.btnExamination.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnExamination.OnPressedState.IconLeftImage = null;
            this.btnExamination.OnPressedState.IconRightImage = null;
            this.btnExamination.Size = new System.Drawing.Size(217, 48);
            this.btnExamination.TabIndex = 10;
            this.btnExamination.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnExamination.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnExamination.TextMarginLeft = 0;
            this.btnExamination.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnExamination.UseDefaultRadiusAndThickness = true;
            this.btnExamination.Click += new System.EventHandler(this.btnExamination_Click);
            // 
            // btnLaboratory
            // 
            this.btnLaboratory.AllowAnimations = true;
            this.btnLaboratory.AllowMouseEffects = true;
            this.btnLaboratory.AllowToggling = false;
            this.btnLaboratory.AnimationSpeed = 200;
            this.btnLaboratory.AutoGenerateColors = false;
            this.btnLaboratory.AutoRoundBorders = false;
            this.btnLaboratory.AutoSizeLeftIcon = true;
            this.btnLaboratory.AutoSizeRightIcon = true;
            this.btnLaboratory.BackColor = System.Drawing.Color.Transparent;
            this.btnLaboratory.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnLaboratory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLaboratory.BackgroundImage")));
            this.btnLaboratory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLaboratory.ButtonText = "Laboratory";
            this.btnLaboratory.ButtonTextMarginLeft = 0;
            this.btnLaboratory.ColorContrastOnClick = 45;
            this.btnLaboratory.ColorContrastOnHover = 45;
            this.btnLaboratory.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnLaboratory.CustomizableEdges = borderEdges8;
            this.btnLaboratory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLaboratory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLaboratory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLaboratory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLaboratory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLaboratory.Font = new System.Drawing.Font("Open Sans SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLaboratory.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnLaboratory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLaboratory.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLaboratory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLaboratory.IconMarginLeft = 11;
            this.btnLaboratory.IconPadding = 10;
            this.btnLaboratory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLaboratory.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLaboratory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLaboratory.IconSize = 25;
            this.btnLaboratory.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnLaboratory.IdleBorderRadius = 1;
            this.btnLaboratory.IdleBorderThickness = 1;
            this.btnLaboratory.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnLaboratory.IdleIconLeftImage = null;
            this.btnLaboratory.IdleIconRightImage = null;
            this.btnLaboratory.IndicateFocus = false;
            this.btnLaboratory.Location = new System.Drawing.Point(1, 316);
            this.btnLaboratory.Margin = new System.Windows.Forms.Padding(4);
            this.btnLaboratory.Name = "btnLaboratory";
            this.btnLaboratory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLaboratory.OnDisabledState.BorderRadius = 1;
            this.btnLaboratory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLaboratory.OnDisabledState.BorderThickness = 1;
            this.btnLaboratory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLaboratory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLaboratory.OnDisabledState.IconLeftImage = null;
            this.btnLaboratory.OnDisabledState.IconRightImage = null;
            this.btnLaboratory.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(104)))), ((int)(((byte)(94)))));
            this.btnLaboratory.onHoverState.BorderRadius = 1;
            this.btnLaboratory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLaboratory.onHoverState.BorderThickness = 1;
            this.btnLaboratory.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(104)))), ((int)(((byte)(94)))));
            this.btnLaboratory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLaboratory.onHoverState.IconLeftImage = null;
            this.btnLaboratory.onHoverState.IconRightImage = null;
            this.btnLaboratory.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnLaboratory.OnIdleState.BorderRadius = 1;
            this.btnLaboratory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLaboratory.OnIdleState.BorderThickness = 1;
            this.btnLaboratory.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(136)))), ((int)(((byte)(122)))));
            this.btnLaboratory.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnLaboratory.OnIdleState.IconLeftImage = null;
            this.btnLaboratory.OnIdleState.IconRightImage = null;
            this.btnLaboratory.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(68)))), ((int)(((byte)(60)))));
            this.btnLaboratory.OnPressedState.BorderRadius = 1;
            this.btnLaboratory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLaboratory.OnPressedState.BorderThickness = 1;
            this.btnLaboratory.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(68)))), ((int)(((byte)(60)))));
            this.btnLaboratory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLaboratory.OnPressedState.IconLeftImage = null;
            this.btnLaboratory.OnPressedState.IconRightImage = null;
            this.btnLaboratory.Size = new System.Drawing.Size(217, 48);
            this.btnLaboratory.TabIndex = 11;
            this.btnLaboratory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLaboratory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLaboratory.TextMarginLeft = 0;
            this.btnLaboratory.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLaboratory.UseDefaultRadiusAndThickness = true;
            this.btnLaboratory.Click += new System.EventHandler(this.btnLaboratory_Click);
            // 
            // FormMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1344, 821);
            this.Controls.Add(this.bunifuGradientPanel2);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Font = new System.Drawing.Font("Space Grotesk", 8.249999F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.IsMdiContainer = true;
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "FormMain";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "EMRge";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.bunifuGradientPanel2.ResumeLayout(false);
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel LblHospitalMotto;
        private Bunifu.UI.WinForms.BunifuLabel LblHospitalName;
        private Bunifu.UI.WinForms.BunifuLabel LblDate;
        private Bunifu.UI.WinForms.BunifuLabel LblLoggedAs;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel2;

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnLogOut;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDashboard;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPatients;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnExamination;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLaboratory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnInventory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnStaff;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBilling;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
    }
}

